# Generated by Django 5.0.6 on 2024-08-19 09:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('security_app', '0002_alter_user_managers'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='face_image',
        ),
        migrations.AddField(
            model_name='user',
            name='latest_captured_image',
            field=models.ImageField(blank=True, null=True, upload_to='captured_images/'),
        ),
    ]
