# Generated by Django 5.0.6 on 2024-08-19 11:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('security_app', '0003_remove_user_face_image_user_latest_captured_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='face_image',
            field=models.ImageField(blank=True, null=True, upload_to='face_images/'),
        ),
    ]
